event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path("index/", views.IndexView.as_view(), name="index"),
    path("eventlist/", views.EventListView.as_view(), name="eventlist"),
    path("detail/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("CreateEvent/", views.CreateEvent, name="CreateEvent"),
    path("delete/<int:event_id>", views.DeleteEvent, name="delete"),
    path("edit/<int:event_id>", views.edit, name="edit"),
    path("edit/<int:event_id>/update", views.update, name="update"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("event/", include("event.urls")),
    path("admin/", admin.site.urls),
]

event/models.py
from django.db import models


class Event(models.Model):
    event_text = models.CharField(max_length=20)

    def __str__(self):
        return self.event_text


class DateChoice(models.Model):
    event_date = models.CharField(max_length=20)

    def __str__(self):
        return self.event_date


# Create your models here.

event/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponsePermanentRedirect
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import reverse
from django.views import generic

from .models import Event
from .models import DateChoice

# from .models import DateChoice


class IndexView(generic.TemplateView):
    template_name = "event/index.html"


class EventListView(generic.ListView):
    template_name = "event/eventlist.html"
    context_object_name = "latest_event_list"
    model = Event

    def eventlist(self):
        latest_event_list = Event.objects.order_by("event_text")
        context = {"latest_event_list": latest_event_list}
        return render("event/eventlist.html", context)


class DetailView(generic.DetailView):
    template_name = "event/event_detail.html"
    model = Event

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context.update({"event_date_list": DateChoice.objects.order_by("event_date")})
        return context

    def eventdetail(self):
        latest_event_list = Event.objects.order_by("event_text")
        context = {"latest_event_list": latest_event_list}
        return render("event/eventlist.html", context)


def CreateEvent(request):
    c = Event(event_text=request.POST["text"])
    # e = DateChoice(event_date=request.POST["date"])

    if c.event_text != "":
        c.save()

    # if e.event_date != "":
    #     e.save()

    return HttpResponsePermanentRedirect(reverse("event:eventlist"))


def DeleteEvent(request, event_id):
    target_event = Event.objects.get(id=event_id)
    target_event.delete()
    return HttpResponsePermanentRedirect(reverse("event:eventlist"))


def edit(request, event_id):
    target_event = Event.objects.get(id=event_id)
    context = {"event": target_event}
    return render(request, "event/edit.html", context)


def update(request, event_id):
    target_event = Event.objects.get(id=event_id)

    target_event.event_text = request.POST.get("title")
    target_event.save()
    return HttpResponseRedirect(reverse("event:eventlist"))

tyouseikun/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "tyouseikun/index.html"

event/templates/event/detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hello World!
</body>
</html>

event/templates/event/edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- css -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'event/style3.css' %}">
</head>
<body>
    <header>
        <h1>調整くん</h1>
        <nav>
            <ul class="nav_content">
                <li><a href="{% url 'event:index' %}">ホーム</a></li>
                <li><a href="{% url 'event:eventlist' %}">イベント一覧</a></li>
            </ul>
        </nav>
    </header>

    <h2>イベント編集</h2>
    <form action="{% url 'event:update' event.id %}" method="post">
        {% csrf_token %}
        <input class="text_box" type="text" name="title"  value="{{ event.title }}">
        <input class="edit" type="submit" value="編集">
    </form>
</body>
</html>

event/templates/event/event_detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">

</head>
<body>
    <header>
        <h1>調整くん</h1>
        <nav>
            <ul class="nav_content">
                <li><a href="{% url 'event:index' %}">ホーム</a></li>
                <li><a href="{% url 'event:eventlist' %}">イベント一覧</a></li>
            </ul>
        </nav>
    </header>
        <h2>イベント名：{{ event.event_text }}</h2>
</body>
</html>

event/templates/event/eventlist.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- css -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'event/style2.css' %}">

</head>

<body>
    <header>
        <h1>調整くん</h1>
        <nav>
            <ul class="nav_content">
                <li><a href="{% url 'event:index' %}">ホーム</a></li>
                <li><a href="{% url 'event:eventlist' %}">イベント一覧</a></li>
            </ul>
        </nav>
    </header>

    <div class="main_content">
        <h2>イベント一覧</h2>
        {% if latest_event_list %}
        <ul class="event_list">
            {% for event in latest_event_list %}
            <li>{{ event.event_text }}<span><a class="active" href="{% url 'event:edit' event.id %}">編集</a><a class="active" href="{% url 'event:detail' event.pk %}">詳細</a><a class="delete" href="{% url 'event:delete' event.id %}">削除</a></span></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>現在イベントは何も登録されていません</p>
        {% endif %}
    </div>
</body>

</html>

event/templates/event/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
    <!-- css -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'event/style1.css' %}">
</head>

<body>
    <header>
        <h1>調整くん</h1>
        <nav>
            <ul class="nav_content">
                <li><a href="{% url 'event:index' %}">ホーム</a></li>
                <li><a href="{% url 'event:eventlist' %}">イベント一覧</a></li>
            </ul>
        </nav>
    </header>

    <form action="{% url 'event:CreateEvent' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="name">イベント名</label>
            <input type="text" id="name" name="text">
        </fieldset>
        <!-- <fieldset>
            <label for="name">日程</label>
            <input type="text" id="date" name="date">
        </fieldset> -->
        <button type="submit" value="CreateEvent">登録！</button>
    </form>
</body>

</html>